# Generated by Django 6.0.7 on 2026-07-17 09:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='referrer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='page_url',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SiteTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_trackers', to='tracker.project')),
            ],
        ),
        migrations.CreateModel(
            name='PageClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('page_url', models.TextField(blank=True)),
                ('referrer', models.TextField(blank=True)),
                ('element_tag', models.CharField(blank=True, max_length=50)),
                ('element_text', models.CharField(blank=True, max_length=300)),
                ('element_id', models.CharField(blank=True, max_length=200)),
                ('element_class', models.CharField(blank=True, max_length=300)),
                ('element_href', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='tracker.sitetracker')),
            ],
            options={
                'indexes': [models.Index(fields=['tracker', '-clicked_at'], name='tracker_pag_tracker_3ae7fd_idx')],
            },
        ),
    ]
