# Generated by Django 6.0.2 on 2026-08-17 07:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_clickevent_referrer_alter_clickevent_page_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_link', to='tracker.project')),
            ],
        ),
    ]
