# Generated by Django 6.0.2 on 2026-08-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_publicsharelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageclickevent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageclickevent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
